---
- hosts: all
  become: true

  vars:
    python_versions: [3.4]
    apt_upgrade_system_enabled: no
    #python_versions: [2.7],
    #python_install: [virtualenv]

  pre_tasks:
    - name: Ensure build dependencies are installed (RedHat).
      yum: name=which state=present
      when: ansible_os_family == 'RedHat'

  roles:
    #- role_under_test
    - { role: ./ }

  tasks:
    - name: Check python
      command: which python
      register: python_path

    - debug:
        msg: "Python was installed in {{python_path.stdout}}"

    - fail:
        msg: "Python Not Found, tests failed."
      when: python_path.stdout != "/usr/bin/python"

 #   - command -v python || exit 1
 #   - command -v pip || exit 1
 #   - command -v virtualenv || exit 1
 #
 #   - command -v python3.4 || exit 1
 #   - command -v pip3.4 || exit 1
